### ISSUE TITLE
Support for sentinel

### ISSUE THREAD

**Issue by nragon** [Cebeerre/VerisureAPIClient#10]
It would be great if we could add support for sentinel data (temp, air quarlity, humidity, ...)
Also, for future updates, a short description on how to setup mitmproxy and the app.

Regards

**Comment by Cebeerre** [comment]
I don't have a Sentinel device, so a bit tricky to try to figure out how the API works. 

I can maybe write down how to sniff the traffic between the App and the API so someone else can help in that front.

**Comment by nragon** [comment]
That would be great. I can then add that since I have sentinel.

**Comment by ricardofbarros** [comment]
@Cebeerre I can help, I have a sentinel device and I do know how to reverse engineer apps API's.

Do you sniff the traffic using MITM methodology? Does the app pin the certificate? If that's true how do you patch the app?

**Comment by Cebeerre** [comment]
Hi @ricardofbarros ! The last time I did some MITM the app wasn't using certificate pining. I actually used an Android emulator running on my Mac OS instead of using the phone itself. I just installed the mitmproxy CA and configured the emulator to use the proxy and all the traffic started to show up in the logs ... so, pretty simple.

If you can actually help, it would be really appreciated ... I'm now really up to my eyes here and I don't have the sentinel stuff !

**Comment by javiermartingonzalez** [comment]
I have sentinel but I don't know wich data do you need? API call details when getting status?

**Comment by Cebeerre** [comment]
Hi @javiermartingonzalez 

We basically need to see the actual API call. Take a look here:

https://github.com/Cebeerre/SecuritasDirectAPI

You'll see how the Securitas API works. 

The procedure basically involves putting some MITM proxy between the Mobile App and the Internet to be able to see the actual traffic and capture calls like this one while interacting with the sentinel:

```
https://mob2217.securitasdirect.es:12010/WebService/ws.do?request=EST1&ID=AND_________________________vericlient20191029123621&callby=AND_61&Country=ES&lang=es&user=vericlient&pwd=veripass&hash=11111111111&panel=SDVFAST&numinst=2423443
```

The one above for example requests the status of the panel. Typically most of the arguments are static and already known between calls, but we need the ```request=``` and any additional parameters that might be required by the sentinel call.

Thanks !

**Comment by javiermartingonzalez** [comment]
Thank you, mitmt installed and trying to get Sentinel calls.

Using old app I'm getting links like your example, using new app login not working (need to disconnect proxy, login and enter to app to work) but after login only calls to a GraphQL and customers.securitasdirect.es appears.

I keep in touch

**Comment by javiermartingonzalez** [comment]
Click to Sentinel option in app:

`GET https://mob2217.securitasdirect.es:12010/WebService/ws.do?Country=ES&ID=IPH________________(MY_USER_HERE)20211013043722030&request=CONFORT&hash=557820278&user=(MY_USER_HERE)&numinst=(MY_INSTALLATION_HERE)&zone=JX01&lang=es&callby=IPH_61 HTTP/1.1`

Response is:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PET>
  <RES>OK</RES>
  <MSG>Petición procesada correctamente</MSG>
  <DDI>
    <ZONE>JX01</ZONE>
    <ALIAS>Pl_Baja_Cocina</ALIAS>
    <ZONEPREVIOUS></ZONEPREVIOUS>
    <ALIASPREVIOUS></ALIASPREVIOUS>
    <ZONENEXT></ZONENEXT>
    <ALIASNEXT></ALIASNEXT>
    <MOREDDIS>false</MOREDDIS>
    <STATUS>
      <AIRQUALITY>1</AIRQUALITY>
      <AIRQUALITYMSG>Buena</AIRQUALITYMSG>
      <HUMIDITY>44</HUMIDITY>
      <TEMPERATURE>22</TEMPERATURE>
    </STATUS>
    <FORECAST>
      <CITY>Madrid</CITY>
      <CURRENTTEMP>24</CURRENTTEMP>
      <CURRENTHUM>19</CURRENTHUM>
      <DESCRIPTION>Soleado</DESCRIPTION>
      <FORECASTIMG>4</FORECASTIMG>
      <DAY1>
        <FORECASTIMG>4</FORECASTIMG>
        <MAXTEMP>24</MAXTEMP>
        <MINTEMP>14</MINTEMP>
        <VALUE>13/10</VALUE>
      </DAY1>
      <DAY2>
        <FORECASTIMG>4</FORECASTIMG>
        <MAXTEMP>22</MAXTEMP>
        <MINTEMP>13</MINTEMP>
        <VALUE>14/10</VALUE>
      </DAY2>
      <DAY3>
        <FORECASTIMG>6</FORECASTIMG>
        <MAXTEMP>23</MAXTEMP>
        <MINTEMP>15</MINTEMP>
        <VALUE>15/10</VALUE>
      </DAY3>
      <DAY4>
        <FORECASTIMG>10</FORECASTIMG>
        <MAXTEMP>20</MAXTEMP>
        <MINTEMP>15</MINTEMP>
        <VALUE>16/10</VALUE>
      </DAY4>
      <DAY5>
        <FORECASTIMG>10</FORECASTIMG>
        <MAXTEMP>20</MAXTEMP>
        <MINTEMP>14</MINTEMP>
        <VALUE>17/10</VALUE>
      </DAY5>
    </FORECAST>
  </DDI>
  <BLOQ remotereqactive="1" >Estamos mejorando nuestros servicios. Por favor intentelo de nuevo mas tarde. Gracias por confiar en Securitas Direct</BLOQ>
</PET>`

Attached photo of my app screen:

![IMG_1035](https://user-images.githubusercontent.com/17268862/137155834-b7f1ea0f-e9ed-4782-9deb-94fe659f4e9e.PNG)

**Comment by javiermartingonzalez** [comment]
Also checked, after login with the request SRV, I'm getting info of my Sentinel device and associated zone when listing services:

`<SERVICE id="9" idservice="68" act="1" visible="1" codoper="0" totaldevice="0" req="CONFORT" multiplereq="0" numDevicesMR="0" secretword="false" needsdevices="false">
        <COST conf="0" valor="0" textini="Recuerda que por sólo 1e/mes + IVA podrás usar My Verisure de forma ilimitada. Al no tener activado el servicio, cada operación tiene un coste de" textend=" + IVA">Recuerda que por sólo 1e/mes + IVA podrás usar My Verisure de forma ilimitada. Al no tener activado el servicio, cada operación tiene un coste de  0.0  + IVA</COST>
        <DESC>SENTINEL CONFORT</DESC>
        <LOC>Message no available</LOC>
        <SRVATTLIST name="ddiv2values">
          <SRVATT name="temperatura">22</SRVATT>
          <SRVATT name="humedad">44</SRVATT>
          <SRVATT name="airq">Buena</SRVATT>
          <SRVATT name="zone">JX01</SRVATT>
        </SRVATTLIST>
      </SERVICE>`

**Comment by Cebeerre** [comment]
Hi Javier,

Nice one. I guess the Sentinel is pushing the info to their infrastructure in a regular basis, as the panel always requires two requests to get info from it.

If SRV is already returning the Sentinel Data maybe isn't worth adding a new handler for the CONFORT command  ? The SRV handler is already returning a json/dict from all the output.

BR,

**Comment by javiermartingonzalez** [comment]
Yes, recently checked that calling to actual get_sim_and_instibs() the output information comes with Confort info, so I think a new handler is not needed.

`('DESC', 'SENTINEL CONFORT'), ('LOC', 'Message no available'), ('SRVATTLIST', OrderedDict([('@name', 'ddiv2values'), ('SRVATT', [OrderedDict([('@name', 'temperatura'), ('#text', '22')]), OrderedDict([('@name', 'humedad'), ('#text', '44')]), OrderedDict([('@name', 'airq'), ('#text', 'Buena')]), OrderedDict([('@name', 'zone'), ('#text', 'JX01')])])]))])`

**Comment by Cebeerre** [comment]
@nragon , what you think ? You were as well interested in that enhancement. CONFORT is providing a bit more info with the forecast and so on. Not sure is worth it though ...
