### ISSUE TITLE
Component error: securitas_direct - Integration 'securitas_direct' not found.

### ISSUE THREAD

**Issue by nckslater** [Cebeerre/VerisureAPIClient#12]
Hi, 

Just updated to core-2021.7.4 from 2021.5.0

I have reinstalled the HACS repository and copied the files over as the directions say to do in the docs but I get this error: Component error: securitas_direct - Integration 'securitas_direct' not found.

Seen this in the logs: 

`[homeassistant.loader] The custom integration 'securitas_direct' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

**Comment by Cebeerre** [comment]
Hi,

This repo is just about the python pip module that uses the HA integration, not the integration itself. In short, the python module is what does the interaction with the Securitas API itself and the integration interacts with the Python module. 

Not sure where you downloaded the Integration (I was not aware it is available in HACS). @nragon did a new one and did a pull requests to HA core that got stuck. You can maybe just download the code from Nragon's fork and put it in custom-components, it should just work ... 

https://github.com/nragon/core/tree/dev/homeassistant/components/securitas_direct
