### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by artik** [Cebeerre/VerisureAPIClient#2]
Hi @Cebeerre and thanks for this Python script. I'm trying to get the status of my alarm here in Spain, but I'm facing this error:

```
./verisure.py 0000000 MyPass 1987448 SDVFAST ES es 1 EST
Traceback (most recent call last):
  File "./verisure.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Any help ?

**Comment by Cebeerre** [comment]
Hi @artik , you need to install the additional Python modules that are not in the base Python install. Try with:

`$ pip3 install requests`

and 

`$ pip3 install xmltodict`

**Comment by artik** [comment]
Thanks for answer! Status is caught :)
But Answer is strange, no ?

```
python3 verisure.py 0000000 MyPass 1987448 SDVFAST ES es 1 EST

{"PET": {"RES": "OK", "STATUS": "0", "MSG": "Tu Alarma est\u00e1 desconectada", "NUMINST": "1987448", "BLOQ": {"@remotereqactive": "1", "#text": "Estamos mejorando nuestros servicios. Por favor intentelo de nuevo mas tarde. Gracias por confiar en Securitas Direct"}}}
```

**Comment by Cebeerre** [comment]
Indeed, there's something weird on their side that every API answer always includes this "try later" message: "Estamos mejorando nuestros servicios. Por favor intentelo de nuevo mas tarde. Gracias por confiar en Securitas Direct" :)

The interesting asnwer in the json is "RES":"OK" and the STATUS.

**Comment by artik** [comment]
Thanks for your answer, now let's ask for IFTTT or Homebrige :)
