### ISSUE TITLE
IFTTT integration

### ISSUE THREAD

**Issue by artik** [Cebeerre/VerisureAPIClient#3]
Once again, you made a usefull work with this script. Can you provide us the best way to integrate it with IFTTT? Trying to find the best way to do it via webhook ;)

**Comment by Cebeerre** [comment]
Hi @artik, 

The best way I've found to do this is via Flask. It works, but I haven't had time enough to find a proper "production" environment. 

IFTTT requires a proper CA signed certificate, making the whole thing a bit more tricky to self-host this at home. You can try with [https://letsencrypt.org/](https://letsencrypt.org/), it works, but requires quite a lot of work to automate the renewal of the certificate. 

I'm right now exploring the use of AWS Lambda, as the SSL certificates are free as long as you use them on top of their infraestructure/services.

The basic idea, would be as follows, taking into account this creates a basic HTTP authenticated webservice (the urls that you would use in the Webhooks) that would interact with the Verisure API like this as per function "operate_alarm":

```
https://api_username:api_password@XXX.XXX.XXX.XXX/api/v1.0/status
https://api_username:api_password@XXX.XXX.XXX.XXX/api/v1.0/disarm 
```
and so on ...

Another option, would be using [https://ngrok.com/](https://ngrok.com/). This would tunnel with SSL your Webhooks frontend, but all the interaction with the VeriSure API would happen locally at your home server, keeping your Verisure credentials under your own control. 

Flask App example:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from flask import Flask, jsonify
from flask import abort
from flask import make_response
from flask_httpauth import HTTPBasicAuth
import requests
import xmltodict
from datetime import datetime
import time

############################################################
# Adjust for each
############################################################

USER = 'username' # Username in the WebPage
PWD = 'password' # Password in the WebPage
NUMINST = 'inst number' # Installation Number (can be found in the WebPage)
PANEL = 'SDVFAST' # All recent models are SDVFAST
COUNTRY = 'ES'
LANG = 'es'
SECONDS_BETWEEN_REQUESTS=1 # They detect flooding, so be convervative.
YOUR_API_USERNAME='username to protect this webhook API' # Username for your API
YOUR_API_PASSWORD='password to protect this webhook API' # Password for your API

############################################################
# Do not edit from here
############################################################

LOGIN_PAYLOAD = { 'Country': COUNTRY, 'user':USER, 'pwd': PWD, 'lang': LANG }
OP_PAYLOAD = { 'Country': COUNTRY, 'user':USER, 'pwd': PWD, 'lang': LANG, 'panel': PANEL, 'numinst': NUMINST}
OUT_PAYLOAD = { 'Country': COUNTRY, 'user':USER, 'pwd': PWD, 'lang': LANG, 'numinst': '(null)'}
BASE_URL='https://mob2217.securitasdirect.es:12010/WebService/ws.do'
auth = HTTPBasicAuth()
app = Flask(__name__, static_url_path='/static')

@auth.get_password
def get_password(username):
    if username == OUR_API_USERNAME:
        return YOUR_API_PASSWORD
    return None

@auth.error_handler
def unauthorized():
    return make_response(jsonify({'error': 'Unauthorized access'}), 401)

@app.route('/api/v1.0/<alarm_action>', methods=['GET'])
@auth.login_required
def operate_alarm(alarm_action):
    if len(alarm_action) == 0:
        abort(404)
    if alarm_action == 'armoutside':
        output = arm_outside()
    elif alarm_action == 'status':
        output = get_panel_status()
    elif alarm_action == 'disarm':
        output = disarm_all()
    elif alarm_action == 'armnight':
        output = armnight()
    elif alarm_action == 'arm':
        output = arm_total_inside()
    return output

def call_verisure_get(method, parameters):
    time.sleep(SECONDS_BETWEEN_REQUESTS)
    if method == 'GET':
        response = requests.get(BASE_URL, params=parameters)
    elif method == 'POST':
        response = requests.post(BASE_URL, params=parameters)
    if response.status_code == 200:
        output = xmltodict.parse(response.text)
        return output
    else:
        return None

def op_verisure(action,hash,id):
    payload = OP_PAYLOAD
    payload.update({'request': action+'1', 'hash': hash, 'ID': id})
    call_verisure_get('GET',payload)
    payload['request'] = action+'2'
    output = call_verisure_get('GET',payload)
    res = output['PET']['RES']
    while res != 'OK':
        output = call_verisure_get('GET',payload)
        res = output['PET']['RES']
    status = output['PET']['STATUS']
    msg = output['PET']['MSG']
    return { 'result': res, 'status': status, 'message': msg }

def generate_id():
    ID='IPH_________________________'+USER+datetime.now().strftime("%Y%m%d%H%M%S")
    return ID

def get_login_hash():
    payload = LOGIN_PAYLOAD
    payload.update({'request': 'LOGIN', 'ID': generate_id()})
    output = call_verisure_get('POST',payload)
    return output['PET']['HASH']

def logout(hash):
    payload = OUT_PAYLOAD
    payload.update({'request': 'CLS', 'hash': hash, 'ID': generate_id()})
    output = call_verisure_get('GET', payload)
    return output

def get_panel_status():
    hash = get_login_hash()
    id = generate_id()
    status = op_verisure('EST', hash, id)
    logout(hash)
    return jsonify(status)

def arm_outside():
    hash = get_login_hash()
    id = generate_id()
    status = op_verisure('PERI', hash, id)
    logout(hash)
    return jsonify(status)

def arm_total_inside():
    hash = get_login_hash()
    id = generate_id()
    status = op_verisure('ARM', hash, id)
    logout(hash)
    return jsonify(status)

def disarm_all():
    hash = get_login_hash()
    id = generate_id()
    status = op_verisure('DARM', hash, id)
    logout(hash)
    return jsonify(status)

def arm_nigh():
    hash = get_login_hash()
    id = generate_id()
    status = op_verisure('ARMNIGHT', hash, id)
    logout(hash)
    return jsonify(status)

@app.errorhandler(404)
def not_found(error):
    return make_response(jsonify({'error': 'Not found'}), 404)

if __name__ == '__main__':
    app.run(debug=False,threaded=True,host='0.0.0.0',port='5000')
```

**Comment by artik** [comment]
Stunning, I'll have a look tonight, and try to post here the best method I've found ;)

**Comment by Cebeerre** [comment]
Hi @artik, not sure if your intention to integrate this with IFTTT was to use it with Alexa. If this is the case, I've managed to trick Alexa to treat Verisure as a bulb/plug and therefore a voice controlled device. You should have an Echo on the same LAN though. 

See below:

[https://github.com/Cebeerre/VerisureEchoDevice](https://github.com/Cebeerre/VerisureEchoDevice)

**Comment by artik** [comment]
The main goal was to integrate it with Homebridge (to make it work with Apple Homekit). It’s the dev that suggested me to try your script (that works) but because I didn’t have answer yet, I wanted to set up a server with IFTTT links in the meanwhile. But it’s not easy as I tought :)

Orginal post: https://github.com/ptz0n/homebridge-verisure/issues/80

Would be a huge step, as I think most european verisure use the same mobile app. Pity no one made a homebridge plugin yet. Anyway, I stay aware about what happens, and fully available for any kind of test. Securitas is my last piece of homebridge puzzle ;)

**Comment by Cebeerre** [comment]
@artik you can then use the code I just uploaded. This just makes your Pi (or whatever you're using) to be seen in your LAN as a WEMO (Belkin) device via UPnP, and Homebridge has WEMO support. You can get rid of IFTTT with this:

[https://www.npmjs.com/package/homebridge-platform-wemo](https://www.npmjs.com/package/homebridge-platform-wemo)

**Comment by Cebeerre** [comment]
Closing this as it seems the integration with Homebridge is making progress.
