### ISSUE TITLE
ARM full mode?

### ISSUE THREAD

**Issue by artik** [Cebeerre/VerisureAPIClient#4]
A simple question, following your ACTIONS:

```
ACTION:
EST -> STATUS
PERI -> PERIMETER/OUTDOOR
ARM -> ARMED/INDOOR
ARMNIGHT -> ARMED/NIGHT MODE
DARM -> SWITCH OFF EVERYTHING
ACT -> LOG ACTIVITY
```

Is there a way to FULLARM an alarm? As I have PERI and INDOOR, to avoid 2 requests. I tried:

`python3 verisure.py 0000000 MyPass 1371881 SDVFAST ES es 1 PERI ARM`

But it arms only the first parameter. I think securitas offers a full arm mode within one request. Making this request valid would be amazing:

`python3 verisure.py 0000000 MyPass 1371881 SDVFAST ES es 1 FULLARM`

And thanks for your great support!

**Comment by Cebeerre** [comment]
Hi @artik , unfortunately they don't offer a full arm mode. Both in the mobile app and the webpage, you should arm everything separately. 

You can though, create your own command:

```
 elif sys.argv[8] == 'FULLARM':
        output1 = client.arm_total_inside()
        output2 = client.arm_outside()
        output = output1 + output2 
```

**Comment by artik** [comment]
The "Fullmode" button activates both for me in their app (Or maybe I misunderstood something?)

https://i.imgur.com/JaJNHhk.png

(thanks for the command tip BTW!)

**Comment by Cebeerre** [comment]
Nope, this just arms all the inside sensors. If you want in the App to arm everything, you should arm the inside and the perimeter separately. 

You can double check this behaviour using the Status button in the mobile app.

**Comment by artik** [comment]
Absolutely! I didn't even know! So each time I used it, it was in indoor mode only... wow. Thanks a lot for your answers, my turn to work now.
