### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by soth78** [Cebeerre/VerisureAPIClient#6]
Hi,

I've been working with the python script (successfully) for some months, and now it simply stopped working. No error, no nothing, just stays executing indefinitely (days)

I've tried resetting and re-creating the securitas username, no luck. Any advice or anything I can do?

Thanks!

**Comment by Cebeerre** [comment]
Hi @soth78,

Yes, unfortunately Securitas changed some stuff in the API. Now all the API commands that interact with the panel itself do not work (non-panel related like ACT_V2, MYINSTALLATION still work). 

I'm trying to figure out the changes, but it takes some time as it requires from sniffing https traffic between the mobile App and their backend. 

I'll try to see if I can dedicate some minutes later today.

**Comment by Cebeerre** [comment]
Hi @soth78, it was actually quite quick to figure out the change. It just required adding a new parameter required by the API. Could you please try if it works as expected ?

**Comment by soth78** [comment]
Like a charm, works perfectly! thank you so much!!!

**Comment by miquellaboria** [comment]
It works fine again! Thanks!
