### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by nragon** [Cebeerre/VerisureAPIClient#7]
Since this will only work for securitas vendor, shouldn't this be renamed to securitasdirect or pysecuritasdirect?
I'll try to use an HA integration with this lib, but I'm afraid it gets confused with Verisure instead of securitas.

Regards

**Comment by Cebeerre** [comment]
Hi @nragon,

You are maybe right ... but the name actually comes from the mobile app that as you might know is called "My Verisure". The branding mess it's on the company side I'm afraid ... in fact everything is Securitas/Verisure but they use different alarms and therefore backends (APIs) depending on the country. 

Anyway, Segalion is not really using this python script as a module/lib ... he just took my code and did some refactoring to convert it to an HA integration. So no sure how renaming the repo will help ... 

BR

**Comment by nragon** [comment]
I also opened an issue on his side.
My idea is for this repo to become "securitasdirect" or "pysecuritasdirect" as it will only interact with securitas vendor.
Segalion repo would eventually be integrated into HA and stop exist (I believe that's the current workflow for HA components)
Reason I'm trying to change is there could a component called Verisure and another SecuritasDirect, also this repo and Segalion's should complement as it it's another requirement for HA components (use third party api in pypi)

**Comment by Cebeerre** [comment]
Ok, that's fine. I've just rebranded the whole thing ... hopefully everything still works as expected :)

**Comment by nragon** [comment]
I'll start making some pull requests to see if we can get this into pypi.
Thanks
